# Generated by Django 6.0.7 on 2026-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='آدرس سایت')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('telegram_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک تلگرام')),
                ('instagram_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک اینستاگرام')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='لینک گیت هاب')),
                ('linkedin_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک لینکدین')),
                ('site_logo', models.ImageField(upload_to='images/site-setting/', verbose_name='لوگو سایت')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/site-setting/', verbose_name='فاوآیکون سایت')),
                ('copy_right', models.TextField(blank=True, null=True, verbose_name='متن کپی رایت')),
                ('about_us_text', models.TextField(blank=True, null=True, verbose_name='متن  درباره ما')),
                ('site_slogan', models.CharField(blank=True, max_length=300, null=True, verbose_name='شعار سایت')),
                ('contact_us_text', models.TextField(blank=True, null=True, verbose_name='متن تیتر تماس با ما')),
                ('is_main_setting', models.BooleanField(default=False, max_length=250, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات ',
            },
        ),
    ]
