# Generated by Django 6.0.7 on 2026-07-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='contact_us_text',
        ),
    ]
