# Generated by Django 6.0.7 on 2026-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_remove_sitesetting_contact_us_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='country',
            field=models.CharField(default='ایران / تهران', max_length=300, verbose_name='شهر/کشور'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_text',
            field=models.CharField(blank=True, null=True, verbose_name='متن برای ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ساعت کاری'),
        ),
    ]
