# Generated by Django 6.0.7 on 2026-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_sitesetting_country_sitesetting_email_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterKarmaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/footer-karma-gallery/')),
            ],
            options={
                'verbose_name': 'تصاویر گالری کارما فوتری',
                'verbose_name_plural': 'گالری کارما ',
            },
        ),
    ]
