# Generated by Django 6.0.7 on 2026-07-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_footerkarmagallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerkarmagallery',
            name='image',
        ),
        migrations.AddField(
            model_name='footerkarmagallery',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_config.sitesetting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerkarmagallery',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن تیتر'),
        ),
        migrations.CreateModel(
            name='FooterKarmaGalleryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/footer_karma_gallery/', verbose_name='تصویر')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_config.footerkarmagallery', verbose_name='گالری تصاویر')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
