# Generated by Django 6.0.7 on 2026-07-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_remove_footerkarmagallery_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerkarmagallerylist',
            old_name='social_media',
            new_name='gallery',
        ),
    ]
