# Generated by Django 6.0.7 on 2026-07-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0006_rename_social_media_footerkarmagallerylist_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerkarmagallerylist',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='site_config.footerkarmagallery', verbose_name='گالری تصاویر'),
        ),
    ]
