# Generated by Django 6.0.7 on 2026-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0008_sitebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('article_detail', 'صفحه جزئیات مفالات'), ('article_list', 'لیست مقالات')], max_length=50, verbose_name='جایگاه نمایشی'),
        ),
    ]
