# Generated by Django 6.0.7 on 2026-08-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید/عدم تایید')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نظر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='product.productcomment', verbose_name='فرزند')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کابر')),
            ],
            options={
                'verbose_name': 'نظرات محصول',
                'verbose_name_plural': 'نظرات محصولات',
                'ordering': ['created_date'],
            },
        ),
    ]
