# Generated by Django 6.0.7 on 2026-09-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address_order_description_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='processing', max_length=30, verbose_name='وضعیت سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
